//frontend/app/layout.js
import "./globals.css";
import { WebSocketProvider } from "@/hooks/WebSocketProvider"; "@/hooks/WebSocketProvider"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WebSocketProvider>
          {children}
        </WebSocketProvider>
      </body>
    </html>
  );
}
